// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uswwxifwdbegnfzehnyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzd3d4aWZ3ZGJlZ25memVobnlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NDgxMzgsImV4cCI6MjA2MDAyNDEzOH0.hX7mWHv_7i_92Ql_8YxZqhtcTWL6GgwjpD9O3fY82cU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);